//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "GamePage.xaml.h"

void ::MyoGaming::GamePage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///GamePage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::MyoGaming::GamePage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->EnterStoryboard = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(__target);
            }
            break;
        case 2:
            {
                this->ExitStoryboard = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(__target);
            }
            break;
        case 3:
            {
                this->ctr_up = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(this->ctr_up))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_up_PointerEntered);
            }
            break;
        case 4:
            {
                this->ctr_left = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(this->ctr_left))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_left_PointerEntered);
            }
            break;
        case 5:
            {
                this->ctr_down = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(this->ctr_down))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_down_PointerEntered);
            }
            break;
        case 6:
            {
                this->ctr_right = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(this->ctr_right))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_right_PointerEntered);
            }
            break;
        case 7:
            {
                this->pnl_display = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(this->pnl_display))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::pnl_display_PointerEntered);
            }
            break;
        case 8:
            {
                this->txt_rw = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 9:
            {
                this->txt_score = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 10:
            {
                this->img_display = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::MyoGaming::GamePage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


